export const tags = [
  {
    group: "General",
    items: [
      "DCS",
      "Digital Combat Simulator",
      "Mod",
      "Addon",
      "Expansion",
      "Third-Party",
      "Community Mod",
      "Custom Content",
      "Free Mod",
      "Open Beta Compatible",
    ],
  },
  {
    group: "Aircraft",
    items: [
      "Fighter Jet",
      "Bomber",
      "Attack Aircraft",
      "Transport Aircraft",
      "Helicopter",
      "Prototype",
      "Fictional Aircraft",
      "Stealth",
      "VTOL",
      "Carrier-Based",
      "Multirole",
      "Supersonic",
    ],
  },
  {
    group: "Ground Units",
    items: [
      "Tanks",
      "Armored Vehicles",
      "Infantry",
      "SAM System",
      "Artillery",
      "Logistics",
      "Convoys",
      "Anti-Aircraft",
      "Radar",
      "Communications",
      "Ground Warfare",
    ],
  },
  {
    group: "Naval Units",
    items: [
      "Aircraft Carrier",
      "Destroyer",
      "Submarine",
      "Battleship",
      "Frigate",
      "Patrol Boat",
      "Amphibious Assault",
      "Naval Warfare",
    ],
  },
  {
    group: "Weapons & Systems",
    items: [
      "Custom Weapons",
      "Missiles",
      "Rockets",
      "Bombs",
      "Machine Guns",
      "Laser-Guided",
      "Radar-Guided",
      "Electronic Warfare",
      "Targeting Pods",
      "Avionics Upgrade",
    ],
  },
  {
    group: "Maps & Environments",
    items: [
      "Custom Map",
      "New Terrain",
      "Weather Mod",
      "Night Vision",
      "Desert",
      "Arctic",
      "Jungle",
      "Urban Warfare",
      "Real-World Locations",
      "Fictional Locations",
    ],
  },
  {
    group: "Gameplay & Mechanics",
    items: [
      "Realism Enhancement",
      "Flight Model",
      "Damage Model",
      "Cockpit Upgrade",
      "Campaign",
      "Singleplayer Mission",
      "Multiplayer Mission",
      "AI Enhancement",
      "Carrier Ops",
      "Dogfighting",
      "Training",
      "Refueling",
      "Immersion",
      "Historical Accuracy",
    ],
  },
  {
    group: "Visual & Audio",
    items: [
      "Graphics Enhancement",
      "Sound Mod",
      "Texture Pack",
      "HUD Mod",
      "Cockpit Reskin",
      "Night Lighting",
      "Special Effects",
      "VR Optimization",
    ],
  },
  {
    group: "Utilities & Tools",
    items: [
      "Mission Editor Tool",
      "Livery Pack",
      "Custom Skin",
      "Radio Communication",
      "TrackIR Support",
      "Voice Attack",
      "Multiplayer Tools",
      "Performance Optimization",
      "OpenXR",
      "Debugging Tool",
    ],
  },
  {
    group: "Eras & Factions",
    items: [
      "NATO",
      "Russia",
      "USAF",
      "US Navy",
      "RAF",
      "Luftwaffe",
      "Cold War",
      "Modern Warfare",
      "WWI",
      "WWII",
      "Korean War",
      "Vietnam War",
      "Gulf War",
    ],
  },
];
